kinematic_plugins:
  search_libraries:
    - tesseract_kinematics_opw_factories
  inv_kin_plugins:
    manipulator:
      default: KDLInvKinChainLMA
      plugins:
        KDLInvKinChainLMA:
          class: KDLInvKinChainLMAFactory
          config:
            base_link: base_link
            tip_link: paint_gun
