kinematic_plugins:
  search_libraries:
    - tesseract_kinematics_opw_factories
  inv_kin_plugins:
    manipulator:
      default: OPWInvKin
      plugins:
        KDLInvKinChainLMA:
          class: KDLInvKinChainLMAFactory
          config:
            base_link: base_link
            tip_link: tool0
        OPWInvKin:
          class: OPWInvKinFactory
          config:
            base_link: base_link
            tip_link: tool0
            params:
              a1: 0.0
              a2: -0.042
              b: 0.00
              c1: 0.3991
              c2: 0.448
              c3: 0.451
              c4: 0.082
              offsets: [0, 0, -1.57079632679, 0, 0, 0]
              sign_corrections: [1, 1, 1, 1, 1, 1]
